### ISSUE TITLE
Error JSON.parse(eventParams) 

### ISSUE THREAD

**Issue by sokolov09** [unlight/prisma-query-log#4]
```
 index.ts: const params: any[] = JSON.parse(eventParams);
```
eventParams not always is json. 
For example:
```js
prisma.Movie.create({
    data: {
        description: `she will give him ten days of "love," at blabla....`,
    } 
})
```
Params in this case:
```
["she will give him ten days of "love," at blabla...."]
```
This is not valid json string.

Versions:
```
    "prisma": "^3.7.0",
    "prisma-query-log": "^3.1.0",
```
Error:
```
SyntaxError: Unexpected token l in JSON at position ...
```

**Comment by unlight** [comment]
Please, specify which db driver are you using.

**Comment by sokolov09** [comment]
db postgres

**Comment by sokolov09** [comment]
demo error you can see [here](https://github.com/sokolov09/demo-prisma-query-log/)

**Comment by unlight** [comment]
I think it will be not possible to detect boundaries of strings with commas and quotes.

I will wrap json parse to try catch for now.

**Comment by unlight** [comment]
Create bug in prisma
https://github.com/prisma/prisma/issues/12441
